import type { Metadata } from "next";
import Link from "next/link";
import {ToastContainer} from "react-toastify";

export const metadata: Metadata = {
  title: "Đăng ký tài khoản",
  description: "Generated by create next app",
};

export default function RegisterLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <main className="flex justify-center items-center bg-brand-primary h-screen">
      <ToastContainer/>
      {children}
    </main>
  );
}
