import Footer from "@/app/(client)/_components/Footer";
import Header from "@/app/(client)/_components/Header";
import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "trang chủ",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col min-h-screen">
      <Header />
      <main className="flex-grow container mx-auto px-4">{children}</main>
      <Footer />
    </div>
  );
}
