import type { Metadata } from "next";
import { Roboto } from "next/font/google";

const roboto = Roboto({ subsets: ["vietnamese"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default function Admin({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <main className={roboto.className}>{children}</main>;
}
