import type { Metadata } from "next";


export const metadata: Metadata = {
    title: "trang chủ",
    description: "Generated by create next app",
};

export default function HomeLayout({
                                           children,
                                       }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <main className="flex justify-center items-center h-screen">
            {children}
        </main>
    );
}
